- name: "Global labeler"

  uses: jimschubert/labeler-action@v2

enable:
  issues: true
  prs: true

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
#    - 'branches' is an optional array of branch names (or patterns) to limit labeling according to PR target branch
labels:
  'Администрация':
      - '\bадмин[истрация]?\b'
      - '\badmin\b'
  'Баг':
      - '\bбаг[и]?\b'
      - '\bbug:\b'
  'Баланс':
      - '\bбаланс\b'
      - '\bbalance:\b'
  'Вопрос':
      - '\bвопрос\b'
  'Грамматика и правильность написания'
      - '\bграмматика\b'
      - '\bspellcheck:\b'
  'Нужна Помощь':
      - '\bпомогите( мне)?\b'
    exclude:
      - '\b\[тест(инг)?\]\b'
  'Не мержить':
      - '\bне мержить\b'
      - '\bне мерджить\b'
  'Рефактор':
      - '\bрефактор\b'
      - '\brefactor:\b'
  'Соединение с Апстримом':
      - '\bапстрим\b'
  'Удаление':
      - '\bудаление\b'
      - '\bудаляем\b'
      - '\bdel:\b'
  'Улучшение кода':
      - '\bулучшенние( кода)?\b'
      - '\bcode:\b'
  'Усовершенствование':
      - '\bулучшенние\b'
  'Фишка':
      - '\bмехан[ника]?\b'
      - '\bфишка\b'
      - '\badd:\b'
      - '\bmadd:\b'
  'Чиним':
      - '\bфикс[им]?\b'
      - '\bчиним\b'
      - '\bfix:\b'
  'Quality of Life':
      - '\bqol:\b'
