- name: "Global labeler"

  uses: jimschubert/labeler-action@v2

enable:
  issues: true
  prs: true

labels:
  'Администрация':
      - '\bадмин[истрация]?\b'
      - '\badmin\b'
  'Баг':
      - '\bбаг[и]?\b'
      - '\bbug:\b'
  'Баланс':
      - '\bбаланс\b'
      - '\bbalance:\b'
  'Вопрос':
      - '\bвопрос\b'
  'Грамматика и правильность написания'
      - '\bграмматика\b'
      - '\bspellcheck:\b'
  'Нужна Помощь':
      - '\bпомогите( мне)?\b'
    exclude:
      - '\b\[тест(инг)?\]\b'
  'Не мержить':
      - '\bне мержить\b'
      - '\bне мерджить\b'
  'Рефактор':
      - '\bрефактор\b'
      - '\brefactor:\b'
  'Соединение с Апстримом':
      - '\bапстрим\b'
  'Удаление':
      - '\bудаление\b'
      - '\bудаляем\b'
      - '\bdel:\b'
  'Улучшение кода':
      - '\bулучшенние( кода)?\b'
      - '\bcode:\b'
  'Усовершенствование':
      - '\bулучшенние\b'
  'Фишка':
      - '\bмехан[ника]?\b'
      - '\bфишка\b'
      - '\badd:\b'
      - '\bmadd:\b'
  'Чиним':
      - '\bфикс[им]?\b'
      - '\bчиним\b'
      - '\bfix:\b'
  'Quality of Life':
      - '\bqol:\b'
