name: "Search for Conflicts"
on:
  push:
  pull_request_target:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: check if prs are conflicts
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "Конфликты"
          removeOnDirtyLabel: "Конфликты не обнаружены"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "В пулл-реквесте присутствуют конфликты, решите их."
          commentOnClean: "Конфликты решены, всегда будьте готовы получать ещё."
